### ISSUE TITLE
Failed Building the product

### ISSUE THREAD

**Issue by deepjyotigoswami91** [mosh-hamedani/organic-shop#3]
ERROR in Error: Template parse errors:
Can't bind to 'items' since it isn't a known property of 'data-table'.
1. If 'data-table' is an Angular component and it has 'items' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

<data-table
  [ERROR ->][items]="items"
  [itemCount]="itemCount"
  (reload)="reloadItems($event)"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@11:2
Can't bind to 'itemCount' since it isn't a known property of 'data-table'.
1. If 'data-table' is an Angular component and it has 'itemCount' input, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<data-table
  [items]="items"
  [ERROR ->][itemCount]="itemCount"
  (reload)="reloadItems($event)"
>
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@12:2
Can't bind to 'property' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'property' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
>
  <data-table-column
    [ERROR ->][property]="'title'"
    [header]="'Title'"
    [sortable]="true"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@16:4
Can't bind to 'header' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'header' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <data-table-column
    [property]="'title'"
    [ERROR ->][header]="'Title'"
    [sortable]="true"
    [resizable]="true"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@17:4
Can't bind to 'sortable' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'sortable' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    [property]="'title'"
    [header]="'Title'"
    [ERROR ->][sortable]="true"
    [resizable]="true"
  >
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@18:4
Can't bind to 'resizable' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'resizable' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    [header]="'Title'"
    [sortable]="true"
    [ERROR ->][resizable]="true"
  >
  </data-table-column>
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@19:4
'data-table-column' is not a known element:
1. If 'data-table-column' is an Angular component, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  (reload)="reloadItems($event)"
>
  [ERROR ->]<data-table-column
    [property]="'title'"
    [header]="'Title'"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@15:2
Can't bind to 'property' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'property' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  </data-table-column>
  <data-table-column
    [ERROR ->][property]="'price'"
    [header]="'Price'"
    [sortable]="true"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@23:4
Can't bind to 'header' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'header' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
  <data-table-column
    [property]="'price'"
    [ERROR ->][header]="'Price'"
    [sortable]="true"
    [resizable]="true"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@24:4
Can't bind to 'sortable' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'sortable' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    [property]="'price'"
    [header]="'Price'"
    [ERROR ->][sortable]="true"
    [resizable]="true"
  >
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@25:4
Can't bind to 'resizable' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'resizable' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
    [header]="'Price'"
    [sortable]="true"
    [ERROR ->][resizable]="true"
  >
  <ng-template #dataTableCell let-item="item">
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@26:4
'data-table-column' is not a known element:
1. If 'data-table-column' is an Angular component, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
  >
  </data-table-column>
  [ERROR ->]<data-table-column
    [property]="'price'"
    [header]="'Price'"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@22:2
Can't bind to 'property' since it isn't a known property of 'data-table-column'.
1. If 'data-table-column' is an Angular component and it has 'property' input, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

 <data-table-column
    [ERROR ->][property]="'$key'"
 >
   <ng-template #dataTableCell let-item="item">
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@34:4
'data-table-column' is not a known element:
1. If 'data-table-column' is an Angular component, then verify that it is part of this module.
2. If 'data-table-column' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
 </data-table-column>

 [ERROR ->]<data-table-column
    [property]="'$key'"
 >
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@33:1
'data-table' is not a known element:
1. If 'data-table' is an Angular component, then verify that it is part of this module.
2. If 'data-table' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
</p>

[ERROR ->]<data-table
  [items]="items"
  [itemCount]="itemCount"
"): ng:///C:/oshop/src/app/admin/components/admin-products/admin-products.component.html@10:0
    at Error (native)
    at syntaxError (C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:1729:34)
    at TemplateParser.parse (C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:12826:19)
    at AotCompiler._compileComponent (C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:24054:39)
    at C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:23935:55
    at Array.forEach (native)
    at AotCompiler._compileImplFile (C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:23918:20)
    at C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:23829:87
    at Array.map (native)
    at AotCompiler.emitAllImpls (C:\oshop\node_modules\@angular\compiler\bundles\compiler.umd.js:23829:52)
    at CodeGenerator.emit (C:\oshop\node_modules\@angular\compiler-cli\src\codegen.js:42:46)
    at C:\oshop\node_modules\@angular\compiler-cli\src\codegen.js:33:61
    at process._tickCallback (internal/process/next_tick.js:109:7)

**Comment by deepjyotigoswami91** [comment]
"$ng serve" is working fine
but "$ng build --prod" isn't working for me

**Comment by JorisCornelis** [comment]
use: $ng build --prod --aot=false
because you want to use the  plugin for datatables
